apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testingArg
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JagadeeshKrishnaSNunna/crossplaneTest.git
    targetRevision: HEAD
    path: res
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook
