apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: < Git Repo URL Address >
    targetRevision: HEAD
    path: < Target Directory Name>
  destination:
    server: https://kubernetes.default.svc
    namespace: k8s
  
  syncPolicy:
    syncOptions:
      - CreateNameSpace=true
    
    automated:
      selfHeal: true
      prune: true
