apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testing-arg
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JagadeeshKrishnaSNunna/crossplaneTest.git
    targetRevision: HEAD
    path: res
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  
  syncPolicy:
    syncOptions:
      - CreateNameSpace=true
    
    automated:
      selfHeal: true
      prune: true
